# Generated by Django 2.1.7 on 2019-04-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
